version: "3.7"
services:

  spider:
    build: ./spider_app 
    container_name: spider
    ports:
      - "8001:8001"
    expose:
      - 8001
    restart: always
    depends_on:
      - db
    volumes:
      - /Users/pablo.sanderson/repos/z-pablo/jobjob:/home/ubuntu/jobjob
    command: /bin/bash -c "sleep 5; uvicorn jobjob.spider_app.spider_api:app --reload --host 0.0.0.0 --port 8001" 

  webapp:
    build: ./webapp 
    container_name: webapp
    ports:
      - "8000:8000"
    expose:
      - 8000
    restart: always
    depends_on:
      - db
    volumes:
      - /Users/pablo.sanderson/repos/z-pablo/jobjob:/home/ubuntu/jobjob
    command: /bin/bash -c "sleep 5; uvicorn jobjob.webapp.webapp_api:app --reload --host 0.0.0.0 --port 8000"

  db:
    image: postgres:12
    container_name: db
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: postgres
    restart: always

volumes:
  postgres_data:

# frontend:
# queue:
# monitoring:
