name: jobjob
dependencies:
  - python=3.8.*
  - pytest=5.4.*
  - pytest-cov=2.8.*
  - pylint=2.4.*
  - black=19.*

  # All services
  - psycopg2=2.8.4
  - sqlalchemy=1.3.*

  # Spiderapp
  - feedparser=5.2.*
  - lxml=4.5.*

  # Webapp
  - requests=2.23.*
  
  - pip:
    - uvicorn==0.11.3
    - fastapi==0.52.0
    - python-multipart==0.0.5
